#!/usr/bin/env groovy

library(
    identifier: 'git@github.com:areyou0k/JenkinsSharedLibraries.git
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            credentialsId: '66417514-8043-45e2-8d7a-40f401ed557a',
            id: '66417514-8043-45e2-8d7a-40f401ed557a',
            remote: 'git@github.com:areyou0k/JenkinsSharedLibraries.git',
            traits: [
                [
                    $class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait'
                ]
            ]
        ]
    )
)

env.CICD_TYPE = 'AndroidApp'
pipelineEntry()
