#!/usr/bin/env groovy

library(
    identifier: 'github.com:BruceLEO1969/JenkinsSharedLibraries@master',
    changelog: false,
    retriever: modernSCM(
        [
            $class: 'GitSCMSource',
            credentialsId: 'archon-github',
            id: 'archon-github',
            remote: 'git@github.com:BruceLEO1969/JenkinsSharedLibraries.git',
            traits: [
                [
                    $class: 'jenkins.plugins.git.traits.BranchDiscoveryTrait'
                ]
            ]
        ]
    )
)

env.CICD_TYPE = 'AndroidApp'
pipelineEntry()
